import { Inter } from "next/font/google";
import "./globals.css";
import Background from "@/components/background/background";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="relative z-10">{children}</div>
				<Background />
			</body>
		</html>
	);
}
